name: Build Linux64

on: [push, pull_request]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Update submodules
        run: git submodule update --remote --recursive
        
      - name: Install Boost
        run: sudo apt-get install -y libboost-thread-dev libboost-chrono-dev libboost-system-dev

      - name: Build LuaJIT
        run: |
          mkdir -p external/luajit/linux64
          git clone https://github.com/LuaJIT/LuaJIT.git temp_luajit
          cd temp_luajit && make -j$(nproc)
          cp src/libluajit.a ../external/luajit/linux64/liblua51.a

      - name: Install Premake
        run: |
          wget -q https://github.com/premake/premake-core/releases/download/v5.0.0-beta8/premake-5.0.0-beta8-linux.tar.gz
          tar -xzf premake-5.0.0-beta8-linux.tar.gz
          chmod +x premake5

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y g++-multilib libboost-dev
          
      - name: Install Multilib
        run: sudo apt-get update && sudo apt-get install -y g++-multilib

      - name: Build Project
        run: |
          PROJECT_GENERATOR_VERSION=3 ./premake5 gmake --gmcommon=external/garrysmod_common --arch=x64
          make -C projects/linux/gmake config=release_x64

