name: Build Linux64
 
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Update submodules
        run: git submodule update --remote --recursive
        
      - name: Install Boost
        run: sudo apt-get install -y libboost-thread-dev libboost-chrono-dev libboost-system-dev

      - name: Build LuaJIT
        run: |
          mkdir -p external/luajit/linux64
          git clone https://github.com/LuaJIT/LuaJIT.git temp_luajit
          cd temp_luajit && make -j$(nproc)
          cp src/libluajit.a ../external/luajit/linux64/liblua51.a

      - name: Install Premake
        run: |
          wget -q https://github.com/premake/premake-core/releases/download/v5.0.0-beta8/premake-5.0.0-beta8-linux.tar.gz
          tar -xzf premake-5.0.0-beta8-linux.tar.gz
          chmod +x premake5

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y g++-multilib libboost-dev
          
      - name: Install Multilib
        run: sudo apt-get update && sudo apt-get install -y g++-multilib
        
      - name: Patch Source SDK for 64-bit Linux
        run: |
          sed -i 's/sizeof(long) == sizeof(float)/sizeof(int) == sizeof(float)/g' external/garrysmod_common/sourcesdk-minimal/public/tier1/bitbuf.h
          sed -i 's/sizeof(T) == sizeof(long)/sizeof(T) == sizeof(int)/g' external/garrysmod_common/sourcesdk-minimal/public/tier0/threadtools.h
       
      - name: Build Project
        run: |
          mkdir -p libs
          find . -name "*luajit*.so*" -exec cp -u {} libs/libluajit.so \;
          find . -name "*tier0*.so*" -exec cp -u {} libs/libtier0_srv.so \;
          find . -name "*vstdlib*.so*" -exec cp -u {} libs/vstdlib_srv.so \;
          PROJECT_GENERATOR_VERSION=3 ./premake5 gmake --gmcommon=external/garrysmod_common --arch=x86_64
          MF=$(find . -name "gmsv_turbostroi.make" | head -n 1)
          sed -i "s#-l[[:alnum:]]*#$(pwd)/libs/libluajit.so#g" "$MF"
          sed -i 's/linux32/linux64/g' "$MF"
          make -C "$(dirname "$MF")" config=release_x86_64 CXXFLAGS="$CXXFLAGS -fpermissive"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gmsv_turbostroi_linux64
          path: |
            bin/**/*.so
            **/*.so
